drop extension if exists "pg_net";

create extension if not exists "pg_trgm" with schema "public";


  create table "public"."addresses" (
    "address_id" uuid not null default extensions.uuid_generate_v4(),
    "user_id" uuid not null,
    "address_type" character varying(20),
    "street_address" text not null,
    "city" character varying(100) not null,
    "state" character varying(100) not null,
    "postal_code" character varying(20) not null,
    "country" character varying(100) not null,
    "is_default" boolean default false,
    "created_at" timestamp without time zone default now(),
    "address_line1" text,
    "address_line2" text
      );


alter table "public"."addresses" enable row level security;


  create table "public"."admin_key" (
    "id" uuid not null default gen_random_uuid(),
    "key" text,
    "admin" uuid default auth.uid(),
    "created_at" timestamp with time zone
      );


alter table "public"."admin_key" enable row level security;


  create table "public"."cart" (
    "cart_id" uuid not null default extensions.uuid_generate_v4(),
    "user_id" uuid,
    "created_at" timestamp without time zone default now(),
    "updated_at" timestamp without time zone default now()
      );


alter table "public"."cart" enable row level security;


  create table "public"."cart_items" (
    "cart_item_id" uuid not null default extensions.uuid_generate_v4(),
    "cart_id" uuid not null,
    "product_id" uuid not null,
    "quantity" integer not null default 1,
    "added_at" timestamp without time zone default now(),
    "size" text
      );


alter table "public"."cart_items" enable row level security;


  create table "public"."categories" (
    "category_id" uuid not null default extensions.uuid_generate_v4(),
    "category_name" character varying(100) not null,
    "slug" character varying(100) not null,
    "description" text,
    "category_image_url" text,
    "is_active" boolean default true,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."categories" enable row level security;


  create table "public"."categories_backup" (
    "category_id" uuid,
    "category_name" character varying(100),
    "slug" character varying(100),
    "description" text,
    "category_image_url" text,
    "is_active" boolean,
    "created_at" timestamp without time zone
      );



  create table "public"."coupons" (
    "coupon_id" uuid not null default extensions.uuid_generate_v4(),
    "coupon_code" character varying(50) not null,
    "description" text,
    "discount_type" character varying(20),
    "discount_value" numeric(10,2) not null,
    "min_purchase_amount" numeric(10,2) default 0,
    "max_discount_amount" numeric(10,2),
    "usage_limit" integer,
    "usage_count" integer default 0,
    "valid_from" timestamp with time zone not null,
    "valid_until" timestamp with time zone not null,
    "is_active" boolean default true,
    "coupon_type" text default 'PREPAID'::text
      );


alter table "public"."coupons" enable row level security;


  create table "public"."image_resources" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "image_link" text,
    "section_name" text,
    "redirect_route" text
      );


alter table "public"."image_resources" enable row level security;


  create table "public"."image_resources_backup" (
    "id" bigint,
    "created_at" timestamp with time zone,
    "image_link" text,
    "section_name" text,
    "redirect_route" text
      );



  create table "public"."order_items" (
    "order_item_id" uuid not null default extensions.uuid_generate_v4(),
    "order_id" uuid not null,
    "product_id" uuid,
    "quantity" integer not null,
    "unit_price" numeric(10,2) not null,
    "total_price" numeric(10,2) not null,
    "ordered_at" timestamp without time zone default now()
      );


alter table "public"."order_items" enable row level security;


  create table "public"."orders" (
    "order_id" uuid not null default extensions.uuid_generate_v4(),
    "user_id" uuid,
    "order_number" character varying(50),
    "order_status" character varying(20) default NULL::character varying,
    "payment_status" character varying(20) not null default NULL::character varying,
    "tax_amount" numeric(10,2) default 0,
    "total_amount" numeric(10,2) not null,
    "shipping_address_id" uuid,
    "order_date" timestamp without time zone default now(),
    "shipped_date" timestamp without time zone,
    "delivered_date" timestamp without time zone,
    "transaction_id" character varying,
    "address_text" text,
    "lock_order" boolean default false,
    "coupon_code" character varying
      );


alter table "public"."orders" enable row level security;


  create table "public"."payments" (
    "payment_id" uuid not null default extensions.uuid_generate_v4(),
    "order_id" uuid not null,
    "payment_method" character varying(50) not null,
    "transaction_id" character varying(255),
    "amount" numeric(10,2) not null,
    "payment_status" character varying(20) default 'pending'::character varying,
    "payment_date" timestamp without time zone default now()
      );



  create table "public"."product_images" (
    "image_id" uuid not null default extensions.uuid_generate_v4(),
    "product_id" uuid not null,
    "image_url" text not null
      );


alter table "public"."product_images" enable row level security;


  create table "public"."product_images_backup" (
    "image_id" uuid,
    "product_id" uuid,
    "image_url" text
      );



  create table "public"."products" (
    "product_id" uuid not null default extensions.uuid_generate_v4(),
    "category_id" uuid,
    "product_name" character varying(255),
    "description" text,
    "base_price" numeric(10,2),
    "discount_percentage" numeric(5,2) default 0,
    "final_price" numeric(10,2),
    "stock_quantity" integer default 0,
    "weight_grams" numeric(8,2),
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "subcategory_id" uuid,
    "thumbnail_image" text,
    "size" text[],
    "tags" text[],
    "occasion" text,
    "collection" text,
    "listed_status" boolean default false,
    "sku" text,
    "home_visibility" boolean not null default true
      );


alter table "public"."products" enable row level security;


  create table "public"."products_backup" (
    "product_id" uuid,
    "category_id" uuid,
    "product_name" character varying(255),
    "description" text,
    "base_price" numeric(10,2),
    "discount_percentage" numeric(5,2),
    "final_price" numeric(10,2),
    "stock_quantity" integer,
    "weight_grams" numeric(8,2),
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone,
    "subcategory_id" uuid,
    "thumbnail_image" text,
    "size" text[],
    "tags" text[],
    "occasion" text,
    "collection" text,
    "listed_status" boolean,
    "sku" text
      );



  create table "public"."review_images" (
    "review_image_id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "review_id" uuid not null,
    "review_image_url" text
      );


alter table "public"."review_images" enable row level security;


  create table "public"."reviews" (
    "review_id" uuid not null default extensions.uuid_generate_v4(),
    "product_id" uuid not null,
    "user_id" uuid not null,
    "rating" integer not null,
    "title" character varying(255),
    "review_text" text,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."reviews" enable row level security;


  create table "public"."sub_categories" (
    "subcategory_id" uuid not null default gen_random_uuid(),
    "category_id" uuid default gen_random_uuid(),
    "subcategory_name" text,
    "subcategory_image_url" text,
    "is_active" boolean default true
      );


alter table "public"."sub_categories" enable row level security;


  create table "public"."users" (
    "user_id" uuid not null default extensions.uuid_generate_v4(),
    "email" character varying(255),
    "password_hash" character varying(255),
    "first_name" character varying(100),
    "last_name" character varying(100),
    "phone_number" character varying(20),
    "is_active" boolean default true,
    "created_at" timestamp without time zone default now(),
    "updated_at" timestamp without time zone default now()
      );


alter table "public"."users" enable row level security;


  create table "public"."wishlist" (
    "wishlist_id" uuid not null default extensions.uuid_generate_v4(),
    "user_id" uuid not null
      );


alter table "public"."wishlist" enable row level security;


  create table "public"."wishlist_items" (
    "wishlist_item_id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "wishlist_id" uuid,
    "product_id" uuid
      );


alter table "public"."wishlist_items" enable row level security;

CREATE UNIQUE INDEX addresses_pkey ON public.addresses USING btree (address_id);

CREATE UNIQUE INDEX admin_key_pkey ON public.admin_key USING btree (id);

CREATE UNIQUE INDEX cart_items_pkey ON public.cart_items USING btree (cart_item_id);

CREATE UNIQUE INDEX cart_pkey ON public.cart USING btree (cart_id);

CREATE UNIQUE INDEX cart_user_id_key ON public.cart USING btree (user_id);

CREATE INDEX categories_name_trgm ON public.categories USING gin (category_name public.gin_trgm_ops);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (category_id);

CREATE UNIQUE INDEX categories_slug_key ON public.categories USING btree (slug);

CREATE UNIQUE INDEX coupons_coupon_code_key ON public.coupons USING btree (coupon_code);

CREATE UNIQUE INDEX coupons_pkey ON public.coupons USING btree (coupon_id);

CREATE INDEX idx_addresses_user_id ON public.addresses USING btree (user_id);

CREATE INDEX idx_cart_items_cart ON public.cart_items USING btree (cart_id);

CREATE INDEX idx_cart_items_product ON public.cart_items USING btree (product_id);

CREATE INDEX idx_cart_user ON public.cart USING btree (user_id);

CREATE INDEX idx_coupons_code ON public.coupons USING btree (coupon_code);

CREATE INDEX idx_order_items_order ON public.order_items USING btree (order_id);

CREATE INDEX idx_order_items_product ON public.order_items USING btree (product_id);

CREATE INDEX idx_orders_date ON public.orders USING btree (order_date DESC);

CREATE INDEX idx_orders_number ON public.orders USING btree (order_number);

CREATE INDEX idx_orders_status ON public.orders USING btree (order_status);

CREATE INDEX idx_orders_user ON public.orders USING btree (user_id);

CREATE INDEX idx_payments_order ON public.payments USING btree (order_id);

CREATE INDEX idx_payments_transaction ON public.payments USING btree (transaction_id);

CREATE INDEX idx_product_images_product ON public.product_images USING btree (product_id);

CREATE INDEX idx_products_category ON public.products USING btree (category_id);

CREATE INDEX idx_reviews_product ON public.reviews USING btree (product_id);

CREATE INDEX idx_reviews_user ON public.reviews USING btree (user_id);

CREATE INDEX idx_users_email ON public.users USING btree (email);

CREATE INDEX idx_wishlist_user ON public.wishlist USING btree (user_id);

CREATE UNIQUE INDEX image_resources_pkey ON public.image_resources USING btree (id);

CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (order_item_id);

CREATE UNIQUE INDEX orders_order_number_key ON public.orders USING btree (order_number);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (order_id);

CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (payment_id);

CREATE UNIQUE INDEX product_images_pkey ON public.product_images USING btree (image_id);

CREATE INDEX products_category_id_idx ON public.products USING btree (category_id);

CREATE INDEX products_name_trgm ON public.products USING gin (product_name public.gin_trgm_ops);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (product_id);

CREATE UNIQUE INDEX products_sku_key ON public.products USING btree (sku);

CREATE UNIQUE INDEX review_images_pkey ON public.review_images USING btree (review_image_id);

CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (review_id);

CREATE UNIQUE INDEX sub_categories_pkey ON public.sub_categories USING btree (subcategory_id);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_phone_number_key ON public.users USING btree (phone_number);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (user_id);

CREATE UNIQUE INDEX wishlist_items_pkey ON public.wishlist_items USING btree (wishlist_item_id);

CREATE UNIQUE INDEX wishlist_pkey ON public.wishlist USING btree (wishlist_id);

alter table "public"."addresses" add constraint "addresses_pkey" PRIMARY KEY using index "addresses_pkey";

alter table "public"."admin_key" add constraint "admin_key_pkey" PRIMARY KEY using index "admin_key_pkey";

alter table "public"."cart" add constraint "cart_pkey" PRIMARY KEY using index "cart_pkey";

alter table "public"."cart_items" add constraint "cart_items_pkey" PRIMARY KEY using index "cart_items_pkey";

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."coupons" add constraint "coupons_pkey" PRIMARY KEY using index "coupons_pkey";

alter table "public"."image_resources" add constraint "image_resources_pkey" PRIMARY KEY using index "image_resources_pkey";

alter table "public"."order_items" add constraint "order_items_pkey" PRIMARY KEY using index "order_items_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";

alter table "public"."product_images" add constraint "product_images_pkey" PRIMARY KEY using index "product_images_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."review_images" add constraint "review_images_pkey" PRIMARY KEY using index "review_images_pkey";

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."sub_categories" add constraint "sub_categories_pkey" PRIMARY KEY using index "sub_categories_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."wishlist" add constraint "wishlist_pkey" PRIMARY KEY using index "wishlist_pkey";

alter table "public"."wishlist_items" add constraint "wishlist_items_pkey" PRIMARY KEY using index "wishlist_items_pkey";

alter table "public"."addresses" add constraint "addresses_address_type_check" CHECK (((address_type)::text = ANY ((ARRAY['billing'::character varying, 'shipping'::character varying])::text[]))) not valid;

alter table "public"."addresses" validate constraint "addresses_address_type_check";

alter table "public"."addresses" add constraint "addresses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."addresses" validate constraint "addresses_user_id_fkey";

alter table "public"."cart" add constraint "cart_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cart" validate constraint "cart_user_id_fkey";

alter table "public"."cart" add constraint "cart_user_id_key" UNIQUE using index "cart_user_id_key";

alter table "public"."cart_items" add constraint "cart_items_cart_id_fkey" FOREIGN KEY (cart_id) REFERENCES public.cart(cart_id) ON DELETE CASCADE not valid;

alter table "public"."cart_items" validate constraint "cart_items_cart_id_fkey";

alter table "public"."cart_items" add constraint "cart_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE CASCADE not valid;

alter table "public"."cart_items" validate constraint "cart_items_product_id_fkey";

alter table "public"."categories" add constraint "categories_slug_key" UNIQUE using index "categories_slug_key";

alter table "public"."coupons" add constraint "coupons_coupon_code_key" UNIQUE using index "coupons_coupon_code_key";

alter table "public"."coupons" add constraint "coupons_discount_type_check" CHECK (((discount_type)::text = ANY ((ARRAY['percentage'::character varying, 'fixed'::character varying])::text[]))) not valid;

alter table "public"."coupons" validate constraint "coupons_discount_type_check";

alter table "public"."order_items" add constraint "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE CASCADE not valid;

alter table "public"."order_items" validate constraint "order_items_order_id_fkey";

alter table "public"."order_items" add constraint "order_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."order_items" validate constraint "order_items_product_id_fkey";

alter table "public"."orders" add constraint "orders_order_number_key" UNIQUE using index "orders_order_number_key";

alter table "public"."orders" add constraint "orders_shipping_address_id_fkey" FOREIGN KEY (shipping_address_id) REFERENCES public.addresses(address_id) not valid;

alter table "public"."orders" validate constraint "orders_shipping_address_id_fkey";

alter table "public"."orders" add constraint "orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."orders" validate constraint "orders_user_id_fkey";

alter table "public"."payments" add constraint "payments_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE RESTRICT not valid;

alter table "public"."payments" validate constraint "payments_order_id_fkey";

alter table "public"."product_images" add constraint "product_images_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE CASCADE not valid;

alter table "public"."product_images" validate constraint "product_images_product_id_fkey";

alter table "public"."products" add constraint "products_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(category_id) ON DELETE SET NULL not valid;

alter table "public"."products" validate constraint "products_category_id_fkey";

alter table "public"."products" add constraint "products_sku_key" UNIQUE using index "products_sku_key";

alter table "public"."products" add constraint "products_subcategory_id_fkey" FOREIGN KEY (subcategory_id) REFERENCES public.sub_categories(subcategory_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."products" validate constraint "products_subcategory_id_fkey";

alter table "public"."review_images" add constraint "review_images_review_id_fkey" FOREIGN KEY (review_id) REFERENCES public.reviews(review_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."review_images" validate constraint "review_images_review_id_fkey";

alter table "public"."reviews" add constraint "reviews_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_product_id_fkey";

alter table "public"."reviews" add constraint "reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5))) not valid;

alter table "public"."reviews" validate constraint "reviews_rating_check";

alter table "public"."reviews" add constraint "reviews_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_user_id_fkey";

alter table "public"."sub_categories" add constraint "sub_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(category_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sub_categories" validate constraint "sub_categories_category_id_fkey";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."users" add constraint "users_phone_number_key" UNIQUE using index "users_phone_number_key";

alter table "public"."wishlist" add constraint "wishlist_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."wishlist" validate constraint "wishlist_user_id_fkey";

alter table "public"."wishlist_items" add constraint "wishlist_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."wishlist_items" validate constraint "wishlist_items_product_id_fkey";

alter table "public"."wishlist_items" add constraint "wishlist_items_wishlist_id_fkey" FOREIGN KEY (wishlist_id) REFERENCES public.wishlist(wishlist_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."wishlist_items" validate constraint "wishlist_items_wishlist_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.search_products_fast(q text, result_limit integer DEFAULT 20)
 RETURNS SETOF public.products
 LANGUAGE sql
 STABLE
AS $function$
  select p.*
  from products p
  left join categories c
    on p.category_id = c.category_id
  where
    (
      p.product_name % q
      or c.category_name % q
    )
    and p.listed_status = true
  order by
    greatest(
      similarity(p.product_name, q),
      similarity(c.category_name, q)
    ) desc
  limit result_limit;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."addresses" to "anon";

grant insert on table "public"."addresses" to "anon";

grant references on table "public"."addresses" to "anon";

grant select on table "public"."addresses" to "anon";

grant trigger on table "public"."addresses" to "anon";

grant truncate on table "public"."addresses" to "anon";

grant update on table "public"."addresses" to "anon";

grant delete on table "public"."addresses" to "authenticated";

grant insert on table "public"."addresses" to "authenticated";

grant references on table "public"."addresses" to "authenticated";

grant select on table "public"."addresses" to "authenticated";

grant trigger on table "public"."addresses" to "authenticated";

grant truncate on table "public"."addresses" to "authenticated";

grant update on table "public"."addresses" to "authenticated";

grant delete on table "public"."addresses" to "service_role";

grant insert on table "public"."addresses" to "service_role";

grant references on table "public"."addresses" to "service_role";

grant select on table "public"."addresses" to "service_role";

grant trigger on table "public"."addresses" to "service_role";

grant truncate on table "public"."addresses" to "service_role";

grant update on table "public"."addresses" to "service_role";

grant delete on table "public"."admin_key" to "anon";

grant insert on table "public"."admin_key" to "anon";

grant references on table "public"."admin_key" to "anon";

grant select on table "public"."admin_key" to "anon";

grant trigger on table "public"."admin_key" to "anon";

grant truncate on table "public"."admin_key" to "anon";

grant update on table "public"."admin_key" to "anon";

grant delete on table "public"."admin_key" to "authenticated";

grant insert on table "public"."admin_key" to "authenticated";

grant references on table "public"."admin_key" to "authenticated";

grant select on table "public"."admin_key" to "authenticated";

grant trigger on table "public"."admin_key" to "authenticated";

grant truncate on table "public"."admin_key" to "authenticated";

grant update on table "public"."admin_key" to "authenticated";

grant delete on table "public"."admin_key" to "service_role";

grant insert on table "public"."admin_key" to "service_role";

grant references on table "public"."admin_key" to "service_role";

grant select on table "public"."admin_key" to "service_role";

grant trigger on table "public"."admin_key" to "service_role";

grant truncate on table "public"."admin_key" to "service_role";

grant update on table "public"."admin_key" to "service_role";

grant delete on table "public"."cart" to "anon";

grant insert on table "public"."cart" to "anon";

grant references on table "public"."cart" to "anon";

grant select on table "public"."cart" to "anon";

grant trigger on table "public"."cart" to "anon";

grant truncate on table "public"."cart" to "anon";

grant update on table "public"."cart" to "anon";

grant delete on table "public"."cart" to "authenticated";

grant insert on table "public"."cart" to "authenticated";

grant references on table "public"."cart" to "authenticated";

grant select on table "public"."cart" to "authenticated";

grant trigger on table "public"."cart" to "authenticated";

grant truncate on table "public"."cart" to "authenticated";

grant update on table "public"."cart" to "authenticated";

grant delete on table "public"."cart" to "service_role";

grant insert on table "public"."cart" to "service_role";

grant references on table "public"."cart" to "service_role";

grant select on table "public"."cart" to "service_role";

grant trigger on table "public"."cart" to "service_role";

grant truncate on table "public"."cart" to "service_role";

grant update on table "public"."cart" to "service_role";

grant delete on table "public"."cart_items" to "anon";

grant insert on table "public"."cart_items" to "anon";

grant references on table "public"."cart_items" to "anon";

grant select on table "public"."cart_items" to "anon";

grant trigger on table "public"."cart_items" to "anon";

grant truncate on table "public"."cart_items" to "anon";

grant update on table "public"."cart_items" to "anon";

grant delete on table "public"."cart_items" to "authenticated";

grant insert on table "public"."cart_items" to "authenticated";

grant references on table "public"."cart_items" to "authenticated";

grant select on table "public"."cart_items" to "authenticated";

grant trigger on table "public"."cart_items" to "authenticated";

grant truncate on table "public"."cart_items" to "authenticated";

grant update on table "public"."cart_items" to "authenticated";

grant delete on table "public"."cart_items" to "service_role";

grant insert on table "public"."cart_items" to "service_role";

grant references on table "public"."cart_items" to "service_role";

grant select on table "public"."cart_items" to "service_role";

grant trigger on table "public"."cart_items" to "service_role";

grant truncate on table "public"."cart_items" to "service_role";

grant update on table "public"."cart_items" to "service_role";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."categories_backup" to "anon";

grant insert on table "public"."categories_backup" to "anon";

grant references on table "public"."categories_backup" to "anon";

grant select on table "public"."categories_backup" to "anon";

grant trigger on table "public"."categories_backup" to "anon";

grant truncate on table "public"."categories_backup" to "anon";

grant update on table "public"."categories_backup" to "anon";

grant delete on table "public"."categories_backup" to "authenticated";

grant insert on table "public"."categories_backup" to "authenticated";

grant references on table "public"."categories_backup" to "authenticated";

grant select on table "public"."categories_backup" to "authenticated";

grant trigger on table "public"."categories_backup" to "authenticated";

grant truncate on table "public"."categories_backup" to "authenticated";

grant update on table "public"."categories_backup" to "authenticated";

grant delete on table "public"."categories_backup" to "service_role";

grant insert on table "public"."categories_backup" to "service_role";

grant references on table "public"."categories_backup" to "service_role";

grant select on table "public"."categories_backup" to "service_role";

grant trigger on table "public"."categories_backup" to "service_role";

grant truncate on table "public"."categories_backup" to "service_role";

grant update on table "public"."categories_backup" to "service_role";

grant delete on table "public"."coupons" to "anon";

grant insert on table "public"."coupons" to "anon";

grant references on table "public"."coupons" to "anon";

grant select on table "public"."coupons" to "anon";

grant trigger on table "public"."coupons" to "anon";

grant truncate on table "public"."coupons" to "anon";

grant update on table "public"."coupons" to "anon";

grant delete on table "public"."coupons" to "authenticated";

grant insert on table "public"."coupons" to "authenticated";

grant references on table "public"."coupons" to "authenticated";

grant select on table "public"."coupons" to "authenticated";

grant trigger on table "public"."coupons" to "authenticated";

grant truncate on table "public"."coupons" to "authenticated";

grant update on table "public"."coupons" to "authenticated";

grant delete on table "public"."coupons" to "service_role";

grant insert on table "public"."coupons" to "service_role";

grant references on table "public"."coupons" to "service_role";

grant select on table "public"."coupons" to "service_role";

grant trigger on table "public"."coupons" to "service_role";

grant truncate on table "public"."coupons" to "service_role";

grant update on table "public"."coupons" to "service_role";

grant delete on table "public"."image_resources" to "anon";

grant insert on table "public"."image_resources" to "anon";

grant references on table "public"."image_resources" to "anon";

grant select on table "public"."image_resources" to "anon";

grant trigger on table "public"."image_resources" to "anon";

grant truncate on table "public"."image_resources" to "anon";

grant update on table "public"."image_resources" to "anon";

grant delete on table "public"."image_resources" to "authenticated";

grant insert on table "public"."image_resources" to "authenticated";

grant references on table "public"."image_resources" to "authenticated";

grant select on table "public"."image_resources" to "authenticated";

grant trigger on table "public"."image_resources" to "authenticated";

grant truncate on table "public"."image_resources" to "authenticated";

grant update on table "public"."image_resources" to "authenticated";

grant delete on table "public"."image_resources" to "service_role";

grant insert on table "public"."image_resources" to "service_role";

grant references on table "public"."image_resources" to "service_role";

grant select on table "public"."image_resources" to "service_role";

grant trigger on table "public"."image_resources" to "service_role";

grant truncate on table "public"."image_resources" to "service_role";

grant update on table "public"."image_resources" to "service_role";

grant delete on table "public"."image_resources_backup" to "anon";

grant insert on table "public"."image_resources_backup" to "anon";

grant references on table "public"."image_resources_backup" to "anon";

grant select on table "public"."image_resources_backup" to "anon";

grant trigger on table "public"."image_resources_backup" to "anon";

grant truncate on table "public"."image_resources_backup" to "anon";

grant update on table "public"."image_resources_backup" to "anon";

grant delete on table "public"."image_resources_backup" to "authenticated";

grant insert on table "public"."image_resources_backup" to "authenticated";

grant references on table "public"."image_resources_backup" to "authenticated";

grant select on table "public"."image_resources_backup" to "authenticated";

grant trigger on table "public"."image_resources_backup" to "authenticated";

grant truncate on table "public"."image_resources_backup" to "authenticated";

grant update on table "public"."image_resources_backup" to "authenticated";

grant delete on table "public"."image_resources_backup" to "service_role";

grant insert on table "public"."image_resources_backup" to "service_role";

grant references on table "public"."image_resources_backup" to "service_role";

grant select on table "public"."image_resources_backup" to "service_role";

grant trigger on table "public"."image_resources_backup" to "service_role";

grant truncate on table "public"."image_resources_backup" to "service_role";

grant update on table "public"."image_resources_backup" to "service_role";

grant delete on table "public"."order_items" to "anon";

grant insert on table "public"."order_items" to "anon";

grant references on table "public"."order_items" to "anon";

grant select on table "public"."order_items" to "anon";

grant trigger on table "public"."order_items" to "anon";

grant truncate on table "public"."order_items" to "anon";

grant update on table "public"."order_items" to "anon";

grant delete on table "public"."order_items" to "authenticated";

grant insert on table "public"."order_items" to "authenticated";

grant references on table "public"."order_items" to "authenticated";

grant select on table "public"."order_items" to "authenticated";

grant trigger on table "public"."order_items" to "authenticated";

grant truncate on table "public"."order_items" to "authenticated";

grant update on table "public"."order_items" to "authenticated";

grant delete on table "public"."order_items" to "service_role";

grant insert on table "public"."order_items" to "service_role";

grant references on table "public"."order_items" to "service_role";

grant select on table "public"."order_items" to "service_role";

grant trigger on table "public"."order_items" to "service_role";

grant truncate on table "public"."order_items" to "service_role";

grant update on table "public"."order_items" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."payments" to "anon";

grant insert on table "public"."payments" to "anon";

grant references on table "public"."payments" to "anon";

grant select on table "public"."payments" to "anon";

grant trigger on table "public"."payments" to "anon";

grant truncate on table "public"."payments" to "anon";

grant update on table "public"."payments" to "anon";

grant delete on table "public"."payments" to "authenticated";

grant insert on table "public"."payments" to "authenticated";

grant references on table "public"."payments" to "authenticated";

grant select on table "public"."payments" to "authenticated";

grant trigger on table "public"."payments" to "authenticated";

grant truncate on table "public"."payments" to "authenticated";

grant update on table "public"."payments" to "authenticated";

grant delete on table "public"."payments" to "service_role";

grant insert on table "public"."payments" to "service_role";

grant references on table "public"."payments" to "service_role";

grant select on table "public"."payments" to "service_role";

grant trigger on table "public"."payments" to "service_role";

grant truncate on table "public"."payments" to "service_role";

grant update on table "public"."payments" to "service_role";

grant delete on table "public"."product_images" to "anon";

grant insert on table "public"."product_images" to "anon";

grant references on table "public"."product_images" to "anon";

grant select on table "public"."product_images" to "anon";

grant trigger on table "public"."product_images" to "anon";

grant truncate on table "public"."product_images" to "anon";

grant update on table "public"."product_images" to "anon";

grant delete on table "public"."product_images" to "authenticated";

grant insert on table "public"."product_images" to "authenticated";

grant references on table "public"."product_images" to "authenticated";

grant select on table "public"."product_images" to "authenticated";

grant trigger on table "public"."product_images" to "authenticated";

grant truncate on table "public"."product_images" to "authenticated";

grant update on table "public"."product_images" to "authenticated";

grant delete on table "public"."product_images" to "service_role";

grant insert on table "public"."product_images" to "service_role";

grant references on table "public"."product_images" to "service_role";

grant select on table "public"."product_images" to "service_role";

grant trigger on table "public"."product_images" to "service_role";

grant truncate on table "public"."product_images" to "service_role";

grant update on table "public"."product_images" to "service_role";

grant delete on table "public"."product_images_backup" to "anon";

grant insert on table "public"."product_images_backup" to "anon";

grant references on table "public"."product_images_backup" to "anon";

grant select on table "public"."product_images_backup" to "anon";

grant trigger on table "public"."product_images_backup" to "anon";

grant truncate on table "public"."product_images_backup" to "anon";

grant update on table "public"."product_images_backup" to "anon";

grant delete on table "public"."product_images_backup" to "authenticated";

grant insert on table "public"."product_images_backup" to "authenticated";

grant references on table "public"."product_images_backup" to "authenticated";

grant select on table "public"."product_images_backup" to "authenticated";

grant trigger on table "public"."product_images_backup" to "authenticated";

grant truncate on table "public"."product_images_backup" to "authenticated";

grant update on table "public"."product_images_backup" to "authenticated";

grant delete on table "public"."product_images_backup" to "service_role";

grant insert on table "public"."product_images_backup" to "service_role";

grant references on table "public"."product_images_backup" to "service_role";

grant select on table "public"."product_images_backup" to "service_role";

grant trigger on table "public"."product_images_backup" to "service_role";

grant truncate on table "public"."product_images_backup" to "service_role";

grant update on table "public"."product_images_backup" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."products_backup" to "anon";

grant insert on table "public"."products_backup" to "anon";

grant references on table "public"."products_backup" to "anon";

grant select on table "public"."products_backup" to "anon";

grant trigger on table "public"."products_backup" to "anon";

grant truncate on table "public"."products_backup" to "anon";

grant update on table "public"."products_backup" to "anon";

grant delete on table "public"."products_backup" to "authenticated";

grant insert on table "public"."products_backup" to "authenticated";

grant references on table "public"."products_backup" to "authenticated";

grant select on table "public"."products_backup" to "authenticated";

grant trigger on table "public"."products_backup" to "authenticated";

grant truncate on table "public"."products_backup" to "authenticated";

grant update on table "public"."products_backup" to "authenticated";

grant delete on table "public"."products_backup" to "service_role";

grant insert on table "public"."products_backup" to "service_role";

grant references on table "public"."products_backup" to "service_role";

grant select on table "public"."products_backup" to "service_role";

grant trigger on table "public"."products_backup" to "service_role";

grant truncate on table "public"."products_backup" to "service_role";

grant update on table "public"."products_backup" to "service_role";

grant delete on table "public"."review_images" to "anon";

grant insert on table "public"."review_images" to "anon";

grant references on table "public"."review_images" to "anon";

grant select on table "public"."review_images" to "anon";

grant trigger on table "public"."review_images" to "anon";

grant truncate on table "public"."review_images" to "anon";

grant update on table "public"."review_images" to "anon";

grant delete on table "public"."review_images" to "authenticated";

grant insert on table "public"."review_images" to "authenticated";

grant references on table "public"."review_images" to "authenticated";

grant select on table "public"."review_images" to "authenticated";

grant trigger on table "public"."review_images" to "authenticated";

grant truncate on table "public"."review_images" to "authenticated";

grant update on table "public"."review_images" to "authenticated";

grant delete on table "public"."review_images" to "service_role";

grant insert on table "public"."review_images" to "service_role";

grant references on table "public"."review_images" to "service_role";

grant select on table "public"."review_images" to "service_role";

grant trigger on table "public"."review_images" to "service_role";

grant truncate on table "public"."review_images" to "service_role";

grant update on table "public"."review_images" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";

grant delete on table "public"."sub_categories" to "anon";

grant insert on table "public"."sub_categories" to "anon";

grant references on table "public"."sub_categories" to "anon";

grant select on table "public"."sub_categories" to "anon";

grant trigger on table "public"."sub_categories" to "anon";

grant truncate on table "public"."sub_categories" to "anon";

grant update on table "public"."sub_categories" to "anon";

grant delete on table "public"."sub_categories" to "authenticated";

grant insert on table "public"."sub_categories" to "authenticated";

grant references on table "public"."sub_categories" to "authenticated";

grant select on table "public"."sub_categories" to "authenticated";

grant trigger on table "public"."sub_categories" to "authenticated";

grant truncate on table "public"."sub_categories" to "authenticated";

grant update on table "public"."sub_categories" to "authenticated";

grant delete on table "public"."sub_categories" to "service_role";

grant insert on table "public"."sub_categories" to "service_role";

grant references on table "public"."sub_categories" to "service_role";

grant select on table "public"."sub_categories" to "service_role";

grant trigger on table "public"."sub_categories" to "service_role";

grant truncate on table "public"."sub_categories" to "service_role";

grant update on table "public"."sub_categories" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."wishlist" to "anon";

grant insert on table "public"."wishlist" to "anon";

grant references on table "public"."wishlist" to "anon";

grant select on table "public"."wishlist" to "anon";

grant trigger on table "public"."wishlist" to "anon";

grant truncate on table "public"."wishlist" to "anon";

grant update on table "public"."wishlist" to "anon";

grant delete on table "public"."wishlist" to "authenticated";

grant insert on table "public"."wishlist" to "authenticated";

grant references on table "public"."wishlist" to "authenticated";

grant select on table "public"."wishlist" to "authenticated";

grant trigger on table "public"."wishlist" to "authenticated";

grant truncate on table "public"."wishlist" to "authenticated";

grant update on table "public"."wishlist" to "authenticated";

grant delete on table "public"."wishlist" to "service_role";

grant insert on table "public"."wishlist" to "service_role";

grant references on table "public"."wishlist" to "service_role";

grant select on table "public"."wishlist" to "service_role";

grant trigger on table "public"."wishlist" to "service_role";

grant truncate on table "public"."wishlist" to "service_role";

grant update on table "public"."wishlist" to "service_role";

grant delete on table "public"."wishlist_items" to "anon";

grant insert on table "public"."wishlist_items" to "anon";

grant references on table "public"."wishlist_items" to "anon";

grant select on table "public"."wishlist_items" to "anon";

grant trigger on table "public"."wishlist_items" to "anon";

grant truncate on table "public"."wishlist_items" to "anon";

grant update on table "public"."wishlist_items" to "anon";

grant delete on table "public"."wishlist_items" to "authenticated";

grant insert on table "public"."wishlist_items" to "authenticated";

grant references on table "public"."wishlist_items" to "authenticated";

grant select on table "public"."wishlist_items" to "authenticated";

grant trigger on table "public"."wishlist_items" to "authenticated";

grant truncate on table "public"."wishlist_items" to "authenticated";

grant update on table "public"."wishlist_items" to "authenticated";

grant delete on table "public"."wishlist_items" to "service_role";

grant insert on table "public"."wishlist_items" to "service_role";

grant references on table "public"."wishlist_items" to "service_role";

grant select on table "public"."wishlist_items" to "service_role";

grant trigger on table "public"."wishlist_items" to "service_role";

grant truncate on table "public"."wishlist_items" to "service_role";

grant update on table "public"."wishlist_items" to "service_role";


  create policy "Enable insert for users based on user_id"
  on "public"."addresses"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."addresses"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "update address policy"
  on "public"."addresses"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "No deletions allowed on admin keys"
  on "public"."admin_key"
  as permissive
  for delete
  to public
using (false);



  create policy "No updates allowed on admin keys"
  on "public"."admin_key"
  as permissive
  for update
  to public
using (false);



  create policy "Service role can insert admin keys"
  on "public"."admin_key"
  as permissive
  for insert
  to public
with check ((auth.role() = 'service_role'::text));



  create policy "Users can read their own admin key"
  on "public"."admin_key"
  as permissive
  for select
  to public
using ((auth.uid() = admin));



  create policy "Enable insert for users based on user_id"
  on "public"."cart"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."cart"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Delete policy for users in cart items"
  on "public"."cart_items"
  as permissive
  for delete
  to public
using ((EXISTS ( SELECT 1
   FROM public.cart
  WHERE ((cart.cart_id = cart_items.cart_id) AND (cart.user_id = auth.uid())))));



  create policy "Insert policy for user in cart items"
  on "public"."cart_items"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.cart
  WHERE ((cart.cart_id = cart_items.cart_id) AND (cart.user_id = auth.uid())))));



  create policy "Update policy for users in cart_items"
  on "public"."cart_items"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.cart
  WHERE ((cart.cart_id = cart_items.cart_id) AND (cart.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.cart
  WHERE ((cart.cart_id = cart_items.cart_id) AND (cart.user_id = auth.uid())))));



  create policy "Users can read their own cart items"
  on "public"."cart_items"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.cart
  WHERE ((cart.cart_id = cart_items.cart_id) AND (cart.user_id = auth.uid())))));



  create policy "Enable read access for all users"
  on "public"."categories"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."coupons"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."image_resources"
  as permissive
  for select
  to public
using (true);



  create policy "Enable users to view their own data only"
  on "public"."order_items"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.order_id = order_items.order_id) AND (orders.user_id = auth.uid())))));



  create policy "Enable users to view their own data only"
  on "public"."orders"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."product_images"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."products"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."review_images"
  as permissive
  for select
  to public
using (true);



  create policy "Insert review poilicy for users"
  on "public"."review_images"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.reviews
  WHERE ((reviews.review_id = review_images.review_id) AND (reviews.user_id = auth.uid())))));



  create policy "Enable insert for users based on user_id"
  on "public"."reviews"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."reviews"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."sub_categories"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for users based on user_id"
  on "public"."users"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."users"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Update policy for a user"
  on "public"."users"
  as permissive
  for update
  to public
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));



  create policy "Enable insert for users based on user_id"
  on "public"."wishlist"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."wishlist"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Delete policy for wishlist items"
  on "public"."wishlist_items"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.wishlist
  WHERE ((wishlist.wishlist_id = wishlist_items.wishlist_id) AND (wishlist.user_id = auth.uid())))));



  create policy "Enable users to view their own data only"
  on "public"."wishlist_items"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.wishlist
  WHERE ((wishlist.wishlist_id = wishlist_items.wishlist_id) AND (wishlist.user_id = auth.uid())))));



  create policy "Insert policy for wishlist items"
  on "public"."wishlist_items"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.wishlist
  WHERE ((wishlist.wishlist_id = wishlist_items.wishlist_id) AND (wishlist.user_id = auth.uid())))));


CREATE TRIGGER update_cart_updated_at BEFORE UPDATE ON public.cart FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


